"""
Chat: Handles multi-turn follow-up questions grounded in a research report.
Uses Google Gemini 2.5 Flash (free tier) for fast, context-aware responses.

The report is injected as a system-level grounding document.
Conversation history is passed in full on each request (stateless backend).
"""

import os
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
MODEL = "gemini-2.5-flash"

SYSTEM_TEMPLATE = """You are a research assistant helping a user understand a research report.

The report was auto-generated by an AI research agent. Here is the full report:

--- BEGIN REPORT ---
{report}
--- END REPORT ---

Rules:
- Answer ONLY based on the content of the report above.
- If the answer is not in the report, say: "That topic wasn't covered in this report. You could run a new research query on it."
- Be concise — 2-4 sentences unless the user asks for detail.
- Do not make up facts. Do not speculate beyond the report.
- You may quote short phrases from the report to support your answer.
- Maintain a helpful, conversational tone.
"""

def chat_with_report(
    report: str,
    history: list[dict],
    user_message: str,
) -> str:
    """
    Send a follow-up question grounded in the research report.

    Args:
        report:       The full Markdown report string from the agent.
        history:      List of prior turns: [{"role": "user"|"model", "parts": [str]}]
        user_message: The user's current question.

    Returns:
        The assistant's reply as a plain string.

    Raises:
        RuntimeError on Gemini API failure.
    """
    system_instruction = SYSTEM_TEMPLATE.format(report=report)

    model = genai.GenerativeModel(
        model_name=MODEL,
        system_instruction=system_instruction,
    )

    chat_session = model.start_chat(history=history)

    try:
        response = chat_session.send_message(user_message)
        return response.text.strip()
    except Exception as e:
        raise RuntimeError(f"Gemini API error: {e}")


def format_history_for_gemini(raw_history: list[dict]) -> list[dict]:
    """
    Converts frontend history format to Gemini's expected format.

    Frontend sends: [{"role": "user"|"assistant", "content": str}]
    Gemini expects: [{"role": "user"|"model", "parts": [str]}]
    """
    formatted = []
    for turn in raw_history:
        role = "model" if turn["role"] == "assistant" else "user"
        formatted.append({
            "role": role,
            "parts": [turn["content"]],
        })
    return formatted
