"""
Exporter: Converts a Markdown research report into a styled PDF.
Pipeline: Markdown string → HTML string → PDF bytes (via WeasyPrint).

The generated PDF includes:
  - Styled header with topic title and generation date
  - Clean typography with source links preserved
  - Page numbers in the footer
  - Print-optimized layout (A4)
"""

import markdown
from weasyprint import HTML, CSS
from datetime import datetime, timezone


# ── CSS applied to the PDF (embedded, not a file) ──────────────────────────

PDF_CSS = CSS(string="""
  @page {
    size: A4;
    margin: 2.2cm 2.5cm 2.5cm 2.5cm;

    @bottom-center {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 9pt;
      color: #94a3b8;
      font-family: 'Georgia', serif;
    }
  }

  body {
    font-family: 'Georgia', serif;
    font-size: 11pt;
    line-height: 1.7;
    color: #1a202c;
  }

  .report-meta {
    border-bottom: 2px solid #1a202c;
    padding-bottom: 0.6em;
    margin-bottom: 1.5em;
  }

  .report-meta h1 {
    font-size: 20pt;
    margin: 0 0 0.2em 0;
    color: #1a202c;
  }

  .report-meta .generated {
    font-size: 9pt;
    color: #64748b;
    margin: 0;
  }

  h2 {
    font-size: 14pt;
    margin-top: 1.6em;
    margin-bottom: 0.4em;
    color: #1a202c;
    border-bottom: 1px solid #e2e8f0;
    padding-bottom: 0.2em;
    page-break-after: avoid;
  }

  h3 {
    font-size: 12pt;
    margin-top: 1.2em;
    margin-bottom: 0.3em;
    color: #334155;
    page-break-after: avoid;
  }

  p {
    margin: 0.5em 0;
    orphans: 3;
    widows: 3;
  }

  a {
    color: #2563eb;
    text-decoration: underline;
    word-break: break-all;
  }

  code {
    font-family: 'Courier New', monospace;
    font-size: 9.5pt;
    background: #f1f5f9;
    padding: 1px 4px;
    border-radius: 3px;
  }

  blockquote {
    border-left: 3px solid #cbd5e1;
    margin: 0.8em 0;
    padding: 0.4em 1em;
    color: #475569;
  }

  ul, ol {
    margin: 0.5em 0;
    padding-left: 1.5em;
  }

  li {
    margin-bottom: 0.25em;
  }

  .watermark {
    margin-top: 3em;
    padding-top: 0.75em;
    border-top: 1px solid #e2e8f0;
    font-size: 8.5pt;
    color: #94a3b8;
    text-align: center;
  }
""")


def markdown_to_pdf(topic: str, report_markdown: str) -> bytes:
    """
    Convert a Markdown research report to a styled PDF.

    Args:
        topic:           The original research topic (used as the PDF title).
        report_markdown: Full Markdown string of the report.

    Returns:
        PDF as raw bytes, ready to be streamed as a file download.

    Raises:
        RuntimeError on conversion failure.
    """
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")

    # Convert Markdown → HTML (preserve fenced code blocks and tables)
    body_html = markdown.markdown(
        report_markdown,
        extensions=["fenced_code", "tables", "nl2br"],
    )

    # Wrap in a full HTML document with meta header and watermark
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8"/>
      <title>{topic}</title>
    </head>
    <body>
      <div class="report-meta">
        <h1>{topic}</h1>
        <p class="generated">Generated by Research Agent · {generated_at}</p>
      </div>

      {body_html}

      <div class="watermark">
        Generated by Research Agent · Powered by Groq (Llama 3) + Tavily Search
      </div>
    </body>
    </html>
    """

    try:
        pdf_bytes = HTML(string=full_html).write_pdf(stylesheets=[PDF_CSS])
        return pdf_bytes
    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {e}")
